apiVersion: v1
kind: Service
metadata:
  name: {{ include "tripla-apps.name" . }}-backend-svc
  namespace: {{ include "tripla-apps.namespace" . }}
  labels:
    {{- include "tripla-apps.labels" . | nindent 4 }}
  annotations:
    {{- include "tripla-apps.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
  selector:
    app: backend
    {{- include "tripla-apps.selectorLabels" . | nindent 4 }}