{{- range $component := list "backend" "frontend" }}
  {{- $componentData := index $.Values $component }}
  {{- if and $componentData $componentData.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tripla-apps.name" $ }}-{{ $component }}
  namespace: {{ include "tripla-apps.namespace" $ }}
  labels:
    {{- include "tripla-apps.labels" $ | nindent 4 }}
  annotations:
    {{- include "tripla-apps.annotations" $ | nindent 4 }}
data:
  {{- tpl (toYaml $componentData.config) $ | nindent 2 }}
---
  {{- end }}
{{- end }}
