{{- range $component := list "backend" "frontend" }}
  {{- $componentData := index $.Values $component }}
  {{- if and $componentData $componentData.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tripla-apps.name" $ }}-{{ $component }}
  namespace: {{ include "tripla-apps.namespace" $ }}
  labels:
    {{- include "tripla-apps.labels" $ | nindent 4 }}
  annotations:
    {{- include "tripla-apps.annotations" $ | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := $componentData.secrets }}
  {{ $k }}: {{ tpl $v $ | b64enc | quote }}
  {{- end }}
---
  {{- end }}
{{- end }}
